### ISSUE TITLE
Provide a better error when type names are not equally-qualified in instantiated and received declarations

### ISSUE THREAD

**Issue by NickEntin** [dfed/SafeDI#106]
**Goals**
Make it less painful to debug when you refer to a type in an `Instantiator` by two different names. 

**Design**
Give a more actionable error when we have a type that doesn't match anything, but there's an existing type that is the same name prefixed by another type. For example:

```swift
@Instantiated private let someThing: Instantiated<View>

@Received private let someThing: Instantiated<MyViewController.View>
```

**Comment by dfed** [comment]
`Instantiated<MyViewController.View>` is invalid, since nested types can not be `@Instantiable` in `SafeDI`. However, this is a real pain with `@Forwarded` properties.
