### ISSUE TITLE
Fixit for adding public to a class removes `final`

### ISSUE THREAD

**Issue by MrAdamBoyd** [dfed/SafeDI#38]
**Steps to reproduce**
1. Create new class and declare it `final`
2. Mark it as instantiate with SafeDI
3. Error appears: `Instantiable`-decorated type must be `public` or `open`
4. Apply fixit, class declaration is now `public class XYZ` instead of `public final class XYZ`

**Expected behavior**
Fixit applies `public class`

**Actual behavior**
Fixit applies `public final class`

**Comment by dfed** [comment]
This is a bug in `InstantiableVisitor.processModifiers`. We should be adding to `modifiers` rather than setting them directly.
