### ISSUE TITLE
ForwardingInstantiator typealias for easier declarations

### ISSUE THREAD

**Issue by MrAdamBoyd** [dfed/SafeDI#44]
**Goals**
Take an example class:
```
@Instantiable
public final class MetricsService {
  @Forwarded
  private let user
}
```

If a class wants to instantiate `MetricsService`, they must use this declaration:
```
@Instantiated
private let metricsServiceBuilder: ForwardingInstantiator<MetricsService.ForwardedArguments, MetricsService>
```

However, SafeDI can easily generate another typealias, similar to `forwardedArguments` which makes this declaration shorter:
```
@Instantiated
private let metricsServiceBuilder: MetricsService.ForwardingInstantiator
```

Which would look like this in the codegen:
```
extension MetricsService {
  typealias ForwardingInstantiator = FowardingInstantiator</* forwarded types here */, MetricsService> 
}
```

**Comment by dfed** [comment]
Love this idea! Way less of a mouthful at the call site. Folk utilizing dependency inversion will still need to writ out the full `FowardingInstantiator`... but that's already true today so that's not a big deal.

I would recommend deleting the current `ForwardedArguments` typealias as part of this work to avoid introducing more types. This would be a breaking change, but it's a simple one to adopt and I think it's worth the churn.

**Comment by dfed** [comment]
I just realized: as designed, this new typealias would always have the concrete type as the second generic. We need a way to let consumers decide the second generic when the Instantiable fulfills additional types 🤔

Not sure what that looks like yet. If typealiases can be declared with generics (I don't know if they can!), that'd be a reasonable path forward.

Maybe we only include a generic in the typealias if there are fulfilled additional types?

**Comment by dfed** [comment]
Just played with this. Typealiases can have generics! So if there are additional types we could generate:
```
typealias ForwardingInstantiator<FulfilledType> = FowardingInstantiator</* forwarded types here */, FulfilledType> 
```

Note that you'll need to update `TypeDescription`'s `var propertyType: Property.PropertyType` to return `.forwardingInstantiator` when we encounter a type of this shape. We'll also need to update the code that `throws GenerationError.forwardingInstantiatorGenericDoesNotMatch` to skip validation when there is only one generic.
