### ISSUE TITLE
Add tools for visualizing dependency injection graph

### ISSUE THREAD

**Issue by NickEntin** [dfed/SafeDI#85]
**Goals**
Better ways to visualize your dependency injection graph and understand how a dependency got somewhere, what all uses a dependency, etc.

**Non-Goals**
N/A

**Investigations**
N/A

**Design**
Some prior art in usage patterns from cocoapods-why: https://github.com/square/cocoapods-why

**Comment by dfed** [comment]
It looks relatively easy to utilize [DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) to create a graph. Only real q is what we want the graph to look like
